#pragma once

#include <builtinFonts/notosans_8_regular.h>
#include <builtinFonts/notosans_12_bold.h>
#include <builtinFonts/notosans_12_bolditalic.h>
#include <builtinFonts/notosans_12_italic.h>
#include <builtinFonts/notosans_12_regular.h>
#include <builtinFonts/notosans_14_bold.h>
#include <builtinFonts/notosans_14_bolditalic.h>
#include <builtinFonts/notosans_14_italic.h>
#include <builtinFonts/notosans_14_regular.h>
#include <builtinFonts/notosans_16_bold.h>
#include <builtinFonts/notosans_16_bolditalic.h>
#include <builtinFonts/notosans_16_italic.h>
#include <builtinFonts/notosans_16_regular.h>
#include <builtinFonts/notosans_18_bold.h>
#include <builtinFonts/notosans_18_bolditalic.h>
#include <builtinFonts/notosans_18_italic.h>
#include <builtinFonts/notosans_18_regular.h>
#include <builtinFonts/opendyslexic_10_bold.h>
#include <builtinFonts/opendyslexic_10_bolditalic.h>
#include <builtinFonts/opendyslexic_10_italic.h>
#include <builtinFonts/opendyslexic_10_regular.h>
#include <builtinFonts/opendyslexic_12_bold.h>
#include <builtinFonts/opendyslexic_12_bolditalic.h>
#include <builtinFonts/opendyslexic_12_italic.h>
#include <builtinFonts/opendyslexic_12_regular.h>
#include <builtinFonts/opendyslexic_14_bold.h>
#include <builtinFonts/opendyslexic_14_bolditalic.h>
#include <builtinFonts/opendyslexic_14_italic.h>
#include <builtinFonts/opendyslexic_14_regular.h>
#include <builtinFonts/opendyslexic_8_bold.h>
#include <builtinFonts/opendyslexic_8_bolditalic.h>
#include <builtinFonts/opendyslexic_8_italic.h>
#include <builtinFonts/opendyslexic_8_regular.h>
#include <builtinFonts/ubuntu_10_bold.h>
#include <builtinFonts/ubuntu_10_regular.h>
#include <builtinFonts/ubuntu_12_bold.h>
#include <builtinFonts/ubuntu_12_regular.h>
#include <builtinFonts/pknakhonsawan_12_bold.h>
#include <builtinFonts/pknakhonsawan_12_bolditalic.h>
#include <builtinFonts/pknakhonsawan_12_italic.h>
#include <builtinFonts/pknakhonsawan_12_regular.h>
#include <builtinFonts/pknakhonsawan_14_bold.h>
#include <builtinFonts/pknakhonsawan_14_bolditalic.h>
#include <builtinFonts/pknakhonsawan_14_italic.h>
#include <builtinFonts/pknakhonsawan_14_regular.h>
#include <builtinFonts/pknakhonsawan_16_bold.h>
#include <builtinFonts/pknakhonsawan_16_bolditalic.h>
#include <builtinFonts/pknakhonsawan_16_italic.h>
#include <builtinFonts/pknakhonsawan_16_regular.h>
#include <builtinFonts/pknakhonsawan_18_bold.h>
#include <builtinFonts/pknakhonsawan_18_bolditalic.h>
#include <builtinFonts/pknakhonsawan_18_italic.h>
#include <builtinFonts/pknakhonsawan_18_regular.h>
